# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubsciber', 'verbose_name_plural': 'List of Subscribers'},
        ),
    ]
