# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='b52d7475-b64d-4b77-8499-0cef183fadd4', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 11, 18, 48, 23, 250429)),
        ),
    ]
