# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='edbe8adc-a970-4098-bc76-f1e2aef2e02c', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 10, 18, 43, 46, 704251)),
        ),
    ]
