# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='3c9d2b8c-2659-4187-ba65-b96636a08664', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 16, 14, 21, 22, 355247)),
        ),
    ]
