# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20170803_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='930a3dba-a21d-4522-a9ee-534c03f0b57c', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 10, 19, 5, 38, 815699)),
        ),
    ]
