# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20170511_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='37a60400-65e3-458c-b41d-60a0a0b658cf', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 24, 8, 8, 41, 363364)),
        ),
    ]
