# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20170704_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='ebe72e31-d246-4d0e-88aa-7a740f24b49c', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 12, 8, 27, 13, 927851)),
        ),
    ]
