# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20170803_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='761032cf-17fc-4b02-9441-82930144aa97', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 11, 12, 37, 17, 810171)),
        ),
    ]
