# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20170705_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='a9273fb9-8450-47b4-b0b4-35f629dee544', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 12, 10, 24, 59, 933773)),
        ),
    ]
