# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20170517_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='3bf538f3-2fed-4279-927f-8c59b9b4574b', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 24, 12, 36, 56, 25824)),
        ),
    ]
