# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20170804_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='00983b98-f719-4a48-9a05-6edf84c88a88', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 11, 13, 15, 41, 916734)),
        ),
    ]
