# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20170705_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='5cdf4ddf-7a53-49b0-80f3-d9a28c724250', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 12, 10, 29, 58, 912196)),
        ),
    ]
