# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20170705_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='4937faf1-f1d6-4a16-9935-78557c91142b', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 13, 14, 50, 10, 31455)),
        ),
    ]
