# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20170518_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='fe9f52b1-1f43-4b18-a737-f0caeff1d301', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 26, 5, 56, 14, 899289)),
        ),
    ]
