# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20170519_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='a3c82828-5811-40d9-ab79-ff37b5859ab1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 26, 8, 59, 25, 958137)),
        ),
    ]
