# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_auto_20170706_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='a58caebc-6ab4-4b7d-9460-2766eac35537', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 13, 18, 34, 14, 364810)),
        ),
    ]
