# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_auto_20170706_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='5a7c5f33-bdd5-4f26-b2e4-7d29d816df96', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 14, 8, 28, 9, 525484)),
        ),
    ]
