# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_auto_20170519_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='993a956b-6a05-4138-976e-58d0441fafba', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 28, 14, 10, 31, 457769)),
        ),
    ]
