# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_auto_20170707_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='082d7bf2-24e0-4f48-a05f-418e53404586', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 14, 12, 33, 47, 244773)),
        ),
    ]
