# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_auto_20170521_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='24484195-3496-4d54-854a-2d04a7065471', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 28, 16, 26, 29, 9588)),
        ),
    ]
