# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_auto_20170707_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='9a3b1b0e-221f-4897-bbe1-6aa338cbf48b', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 14, 12, 39, 52, 262188)),
        ),
    ]
