# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_auto_20170521_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='3dc28615-6c94-46ea-b40b-16e68046be4b', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 28, 16, 58, 38, 363863)),
        ),
    ]
