# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_auto_20170707_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='289678d6-52be-4173-9084-03c1f9db1942', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 4, 17, 34, 16, 344886)),
        ),
    ]
