# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_auto_20170522_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='cc89a833-d536-48a9-90f9-7d9f6b4f128b', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 29, 8, 3, 33, 575082)),
        ),
    ]
