# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0014_auto_20170522_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='9e5bf8b6-7c2c-428d-99d8-19e5f47d6ee0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 29, 8, 13, 33, 225383)),
        ),
    ]
