# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0015_auto_20170522_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='5cfce182-0c1a-4b47-9b2a-a3a826a5cf78', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 29, 13, 27, 35, 395249)),
        ),
    ]
