# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_initials',
            field=models.CharField(default='', max_length=100),
        ),
    ]
