# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_remove_userprofile_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_initials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to=settings.AUTH_USER_MODEL),
        ),
    ]
