# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170926_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='parent',
        ),
    ]
