# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170406_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
