# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170426_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order'),
        ),
    ]
