# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170406_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
