# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productsinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
