# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='points',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
