# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170517_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
