# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 08:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170519_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.ProductCategory'),
        ),
    ]
