# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170519_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeChoiceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'attribute choices value',
                'verbose_name_plural': 'attribute choices values',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Product attribute',
                'verbose_name_plural': 'Product attributes',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('has_variants', models.BooleanField(default=True)),
                ('is_shipping_required', models.BooleanField(default=False)),
                ('product_attributes', models.ManyToManyField(blank=True, related_name='products_class', to='products.ProductAttribute')),
                ('variant_attributes', models.ManyToManyField(blank=True, related_name='product_variants_class', to='products.ProductAttribute')),
            ],
            options={
                'verbose_name': 'product class',
                'verbose_name_plural': 'product classes',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='attributes',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.Product'),
        ),
        migrations.AddField(
            model_name='attributechoicevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.ProductAttribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductClass', verbose_name='product classes'),
        ),
        migrations.AlterUniqueTogether(
            name='attributechoicevalue',
            unique_together=set([('name', 'attribute')]),
        ),
    ]
