# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170521_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='offer',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='attribute_values', to='products.AttributeChoiceValue'),
        ),
    ]
