# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170522_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.ProductAttribute'),
        ),
    ]
