# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170522_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='is_shipping_required',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='product_attributes',
        ),
        migrations.AddField(
            model_name='offer',
            name='attributes',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='productclass',
            name='variant_attributes',
            field=models.ManyToManyField(blank=True, related_name='variants_class', to='products.ProductAttribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductClass'),
        ),
    ]
